<?php
/**
 * OutboundCapability
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Glue\SPAPI\OpenAPI\Clients\SupplySources
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Selling Partner API for Supply Sources
 *
 * Manage configurations and capabilities of seller supply sources.
 *
 * The version of the OpenAPI document: 2020-07-01
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Glue\SPAPI\OpenAPI\Clients\SupplySources\Model;

use \ArrayAccess;
use \Glue\SPAPI\OpenAPI\Clients\SupplySources\ObjectSerializer;

/**
 * OutboundCapability Class Doc Comment
 *
 * @category Class
 * @description Outbound capability of a supply source.
 * @package  Glue\SPAPI\OpenAPI\Clients\SupplySources
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class OutboundCapability implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'OutboundCapability';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'is_supported' => 'bool',
        'operational_configuration' => '\Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\OperationalConfiguration',
        'return_location' => '\Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\ReturnLocation',
        'delivery_channel' => '\Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\DeliveryChannel',
        'pickup_channel' => '\Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\PickupChannel'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'is_supported' => null,
        'operational_configuration' => null,
        'return_location' => null,
        'delivery_channel' => null,
        'pickup_channel' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'is_supported' => 'isSupported',
        'operational_configuration' => 'operationalConfiguration',
        'return_location' => 'returnLocation',
        'delivery_channel' => 'deliveryChannel',
        'pickup_channel' => 'pickupChannel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'is_supported' => 'setIsSupported',
        'operational_configuration' => 'setOperationalConfiguration',
        'return_location' => 'setReturnLocation',
        'delivery_channel' => 'setDeliveryChannel',
        'pickup_channel' => 'setPickupChannel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'is_supported' => 'getIsSupported',
        'operational_configuration' => 'getOperationalConfiguration',
        'return_location' => 'getReturnLocation',
        'delivery_channel' => 'getDeliveryChannel',
        'pickup_channel' => 'getPickupChannel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['is_supported'] = $data['is_supported'] ?? null;
        $this->container['operational_configuration'] = $data['operational_configuration'] ?? null;
        $this->container['return_location'] = $data['return_location'] ?? null;
        $this->container['delivery_channel'] = $data['delivery_channel'] ?? null;
        $this->container['pickup_channel'] = $data['pickup_channel'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets is_supported
     *
     * @return bool|null
     */
    public function getIsSupported()
    {
        return $this->container['is_supported'];
    }

    /**
     * Sets is_supported
     *
     * @param bool|null $is_supported is_supported
     *
     * @return self
     */
    public function setIsSupported($is_supported)
    {
        $this->container['is_supported'] = $is_supported;

        return $this;
    }

    /**
     * Gets operational_configuration
     *
     * @return \Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\OperationalConfiguration|null
     */
    public function getOperationalConfiguration()
    {
        return $this->container['operational_configuration'];
    }

    /**
     * Sets operational_configuration
     *
     * @param \Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\OperationalConfiguration|null $operational_configuration operational_configuration
     *
     * @return self
     */
    public function setOperationalConfiguration($operational_configuration)
    {
        $this->container['operational_configuration'] = $operational_configuration;

        return $this;
    }

    /**
     * Gets return_location
     *
     * @return \Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\ReturnLocation|null
     */
    public function getReturnLocation()
    {
        return $this->container['return_location'];
    }

    /**
     * Sets return_location
     *
     * @param \Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\ReturnLocation|null $return_location return_location
     *
     * @return self
     */
    public function setReturnLocation($return_location)
    {
        $this->container['return_location'] = $return_location;

        return $this;
    }

    /**
     * Gets delivery_channel
     *
     * @return \Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\DeliveryChannel|null
     */
    public function getDeliveryChannel()
    {
        return $this->container['delivery_channel'];
    }

    /**
     * Sets delivery_channel
     *
     * @param \Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\DeliveryChannel|null $delivery_channel delivery_channel
     *
     * @return self
     */
    public function setDeliveryChannel($delivery_channel)
    {
        $this->container['delivery_channel'] = $delivery_channel;

        return $this;
    }

    /**
     * Gets pickup_channel
     *
     * @return \Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\PickupChannel|null
     */
    public function getPickupChannel()
    {
        return $this->container['pickup_channel'];
    }

    /**
     * Sets pickup_channel
     *
     * @param \Glue\SPAPI\OpenAPI\Clients\SupplySources\Model\PickupChannel|null $pickup_channel pickup_channel
     *
     * @return self
     */
    public function setPickupChannel($pickup_channel)
    {
        $this->container['pickup_channel'] = $pickup_channel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


